/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nqueens;

import static org.junit.Assert.assertTrue;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

public class AppTest {
	private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
	private final PrintStream originalOut = System.out;

	@Before
	public void setUpStreams() {
		System.setOut(new PrintStream(outContent));
	}

	@After
	public void restoreStreams() {
		System.setOut(originalOut);
	}

	@Test
	public void test_happy_case_input() {
		String[] args = new String[1];
		args[0] = "4";

		App.main(args);

		assertTrue("NumberofSolutions2".equals(outContent.toString().replaceAll("[^A-Za-z0-9]", "")));
	}
}
