/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nqueens;

public class App {
	public String getGreeting() {
		return "Hello World!";
	}

	public static void main(String[] args) {
		System.out.println(new App().getGreeting());

		if (args.length > 0) {
			for (String arg : args) {
				System.out.println("Got argument [" + arg + "]");
			}
		}
	}
}
